id: A79A11898
title: 'The Hook Which Invokes the Blessings: A Supplication to the Life and Liberation
  of Rigdzin Jalü Dorje'
type: translation
pechas:
- I439E206E
- IDF55A94E
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:40:11.637834
  last_modified_at: 2023-01-04 11:40:11.637844
  collections:
  - Do Khyentse Yeshe Dorje Series
  - Works of Tibetan Masters
alignment_to_base:
  I439E206E/8A11: E4E2
  IDF55A94E/B115: E4E2
